#!system/bin/bash
#Author = Mr.ZeeY
#Facebook = Angga Donovan

echo "Sabar Ngentooddd!!!!"|lolcat
sleep 3
clear
echo "WAITING FOR ME"|lolcat
sleep 2
clear
echo $white"10%"
sleep 1
clear
echo $white"27%"
sleep 1
clear
echo $white"35%"
sleep 1
clear
echo $white"43%"
sleep 1
clear
echo $white"55%"
sleep 1
clear
echo $white"76%"
sleep 1
clear
echo $white"88%"
sleep 1
clear
echo $white"95%"
sleep 3
clear
echo $white"100%"
sleep 1
clear
figlet " DONE Memek !!"|lolcat
sleep 1
clear
figlet -f slant Mr.ZeeY Ganz Tq |lolcat
echo "_______________________________________________"|lolcat
echo "Author  : Mr.ZeeY "|lolcat
echo "Facebook : Angga Donovan "|lolcat
echo "Thanks To : Allah Swt"|lolcat
echo "_______________________________________________"|lolcat

sleep 1

pkg install curl
figlet -f slant Ip Lookup |lolcat
echo "Masukkan Domain Target"|lolcat
echo "Example : grab.github.io"|lolcat
echo "Example : github.io"|lolcat
echo "MASUKKAN DOMAIN TARGET Mek : "|lolcat
read web
curl https://api.hackertarget.com/reverseiplookup/?q=$web
echo
